
from enum import Enum

class Block(Enum):
    BLOCK = ' '
    CROSSROAD = '┼'
    ROAD_H = ''
    ROAD_V = '┇'
    STREET_H = '╌'
    STREET_V = '┆'
    TRAIL = '.'
    T_RIGHT = '┤'
    T_LEFT = '├'
    T_TOP = '┬'
    T_BOTTOM = '┴'
    CORNER_NE = '╮'
    CORNER_SE = '╯'
    CORNER_NW = '╭'
    CORNER_SW = '╰'
    BANK = '⊡'
    BLACKSMITH = '⚔'
    CLOTHING_STORE = '✄'
    GROCERY_STORE = '⊞'
    HERBAL_STORE = '⚕'
    INN = '∺'
    PAWN_SHOP = '≗'
    RESIDENCE = '⌂'
    TAVERN = '⌅'
    MAILBOX = '✉'
    PINBOARD = '⌗'
    BARREN = '∷'
    FOREST = '⇞'
    GRASSLAND = '⚘'
    HILL = '◬'
    WATER = '≋'
    WATERSIDE = '⌇'
    GUIDEPOST = '⌘'
    HOT_SPRING = '♨'
    GRAVEYARD = '≏'
    POISON = '☠'
    TAI_ZI = '☯'
    WORKSHOP = '⚒'
    STAIR = '⌥'
    MARTIAL_CLUB = '⋌'
    TEA_STALL = '∸'
    BLACK_SUN = '☀'
    WHITE_SUN = '☼'
    CLOUD = '☁'
    UMBRELLA = '☂'
    SNOWY = '☃'
    GATE = '≙'
    TOWN = '⋔'
    TARGET = '⌖'

# block.py
